### ISSUE TITLE
使用cocoapods导入项目会引起闪退

### ISSUE THREAD

**Issue by LucisBaoshg** [pikacode/EBBannerView#1]
原因，在pods中的xib不是属于mainbundle的

修改：
EBBannerView.m   46行
NSBundle *bundle = [NSBundle bundleForClass:self.class];

EBBannerViewController.m  19行
NSBundle *bundle = [NSBundle bundleForClass:self.class];

可以解决

**Comment by pikacode** [comment]
多谢指出 😊

**Comment by pikacode** [comment]
已经解决问题并重新发布了版本
