### ISSUE TITLE
提示文本（contentLabel）可以多行显示吗？

### ISSUE THREAD

**Issue by TonyYuChufang** [pikacode/EBBannerView#10]
iOS11类型的窗口，似乎不能多行显示

**Comment by deepindo** [comment]
我也有一样的需求，非EBBannerViewStyleiOS9样式 ，但要EBBannerViewStyleiOS9一样的多行可以下拉效果

**Comment by pikacode** [comment]
@TonyYuChufang @deepindo 
暂时不支持，这个需求会在下个版本中更新

**Comment by pikacode** [comment]
@TonyYuChufang @deepindo 
你好，最新版本已经添加该功能 [1.0.6](https://github.com/pikacode/EBBannerView/releases/tag/1.0.6)
