### ISSUE TITLE
下拉查看消息时，手未松开是不是应该一直停留？以及松开手后的停留时间能否单独设置？

### ISSUE THREAD

**Issue by vaintwyt** [pikacode/EBBannerView#16]
如题

**Comment by pikacode** [comment]
确实下拉一直停留应该会好一点。这部分改进下次更新时会加上，但不确定时间。

**Comment by pikacode** [comment]
@vaintwyt 增加了几个对应的属性，新版本了解一下 [1.0.8](https://github.com/pikacode/EBBannerView/releases/tag/1.0.8)
