### ISSUE TITLE
怎么获取推送内容啊   make.content

### ISSUE THREAD

**Issue by zhuhai123** [pikacode/EBBannerView#17]
上个版本还可以
[EBForeNotification handleRemoteNotification:userInfo soundID:1312]; 直接userInfo
现在
EBBannerView *banner = [EBBannerView bannerWithBlock:^(EBBannerViewMaker *make) {
   make.style = EBBannerViewStyleiOS9;//指定系统样式，不指定自动依据系统显示不同样式
   make.style = 9;//展示 iOS9 样式
   make.content = @"MINE eye hath played the painter and hath stelled";
}];
怎么办啊

**Comment by pikacode** [comment]
之前的EBForeNotification里面处理了userinfo，现在的EBBannerView需要自己从userinfo提取出content来赋值

**Comment by zhuhai123** [comment]
不知道怎么获取，求帮忙啊而且ios各个版本都不同

**Comment by pikacode** [comment]
不知道怎么获取推送，可以看我简书的文章
https://www.jianshu.com/p/f57e2045f711
https://www.jianshu.com/p/e9c313df746f
