### ISSUE TITLE
请问如何清除全部通知？？？

### ISSUE THREAD

**Issue by difoi** [pikacode/EBBannerView#19]
你好，试以下方法，都无法清除通知栏显示的通知；
UIApplication.shared.cancelAllLocalNotifications()

也无法获取通知；
let locals = UIApplication.shared.scheduledLocalNotifications

// 使用代码
![image](https://user-images.githubusercontent.com/2200801/40709354-60fce6cc-6428-11e8-9231-5b46f9202605.png)

// 清除代码
![image](https://user-images.githubusercontent.com/2200801/40709398-7ae291fe-6428-11e8-8fb2-17a878d53693.png)

**Comment by pikacode** [comment]
你好，这个问题与本仓库无关，可以加iOSqq交流群345192153跟大家讨论。
