### ISSUE TITLE
iOS12崩溃-label:bug.

### ISSUE THREAD

**Issue by ChinaBaozi** [pikacode/EBBannerView#23]
`+(instancetype)bannerViewWithStyle:(EBBannerViewStyle)style{
    __block EBBannerView *bannerView;
    [sharedBannerViews enumerateObjectsUsingBlock:^(EBBannerView * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
        if (obj.maker.style == style) {
            bannerView = obj;
        }
    }];
    if (bannerView == nil) {
        bannerView = [[NSBundle bundleForClass:self.class] loadNibNamed:@"EBBannerView" owner:nil options:nil][style-9];
        [[NSNotificationCenter defaultCenter] addObserver:bannerView selector:@selector(applicationDidChangeStatusBarOrientationNotification) name:UIApplicationDidChangeStatusBarOrientationNotification object:nil];
        [bannerView addGestureRecognizer];
        [sharedBannerViews addObject:bannerView];
    }
    return bannerView;
}`

12 -9 崩溃

**Comment by pikacode** [comment]
是 1.0.7 吗

**Comment by a6721879** [comment]
同样问题

**Comment by pikacode** [comment]
1.0.7 fix 了

**Comment by ChinaBaozi** [comment]
是的


| |
蔡旸普
邮箱：chinabaozi@yeah.net
|

签名由 网易邮箱大师 定制

在2018年09月19日 14:09，pikacode 写道：

是 1.0.7 吗

**Comment by ChinaBaozi** [comment]
不是，好像是1.0.6


| |
蔡旸普
邮箱：chinabaozi@yeah.net
|

签名由 网易邮箱大师 定制

在2018年10月15日 16:57，蔡旸普 写道：
是的


| |
蔡旸普
邮箱：chinabaozi@yeah.net
|

签名由 网易邮箱大师 定制

在2018年09月19日 14:09，pikacode 写道：

是 1.0.7 吗
