### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by fuhailong** [pikacode/EBBannerView#25]
如果ios8系统加入此工程，推送的内容多行时，UI会有些错位
建议修改下计算行高的逻辑

**Comment by pikacode** [comment]
我用模拟器没看到你说的错位的问题，你可以截图个示意一下吗？

**Comment by fuhailong** [comment]
title:10.16晚间优惠推荐
content:历史新低：CAT男士休闲鞋、必迈女运动鞋、哥伦比亚新款防风帽，快来看看吧~
你的xcode版本高 xib里的默认字体 在ios8上没有

**Comment by pikacode** [comment]
可以了，新版本了解一下 [1.0.8](https://github.com/pikacode/EBBannerView/releases/tag/1.0.8)

**Comment by fuhailong** [comment]
辛苦辛苦  一会试下
