### ISSUE TITLE
没有适配iPhone XR、XS Max

### ISSUE THREAD

**Issue by 1050415251** [pikacode/EBBannerView#27]

**Comment by pikacode** [comment]
哥你用的哪个版本

**Comment by 1050415251** [comment]
主分支的 demo

**Comment by 1050415251** [comment]
tag是108
![这是哪个图片](
https://upload-images.jianshu.io/upload_images/13581931-d829189abc11714c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/414)

**Comment by 1050415251** [comment]
https://www.jianshu.com/p/6949131df96f

**Comment by pikacode** [comment]
@1050415251 已经发布了 [1.0.9](https://github.com/pikacode/EBBannerView/releases/tag/1.0.9) 版本修复了这个问题
