### ISSUE TITLE
xcode8.2下最新版本编译失败

### ISSUE THREAD

**Issue by caiwenshu** [pikacode/EBBannerView#28]
![2019-01-07 6 08 17](https://user-images.githubusercontent.com/1404574/50762279-74cde600-12a7-11e9-8ced-f9221a8e9899.png)

**Comment by pikacode** [comment]
老哥升下级呗，至少 9 以上才能使用这个方法，推荐升级到 10，苹果也马上强制要求升级了

**Comment by caiwenshu** [comment]
好吧~
