### ISSUE TITLE
xcode10.3 编译报错

### ISSUE THREAD

**Issue by pengshengsongcode** [pikacode/EBBannerView#31]
EBBannerView.xib:-1: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7fbbb197dc20> System content for IBCocoaTouchFramework-NineOneAndLater <IBScaleFactorDeviceTypeDescription: 0x7fbbb1990920> scaleFactor=2x'. These intermediate objects were non-nil: (

**Comment by pengshengsongcode** [comment]
/Users/anxianglong/Desktop/YDJ-Original-GApp/Pods/CCActiveNotification/CCActiveNotification/Assets/EBBannerView.xib:-1: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7fbbb197dc20> System content for IBCocoaTouchFramework-NineOneAndLater <IBScaleFactorDeviceTypeDescription: 0x7fbbb1990920> scaleFactor=2x'. These intermediate objects were non-nil: (

**Comment by JanXu-Dev** [comment]
sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService

clean up
rebuild
