### ISSUE TITLE
iOS 13显示不完整

### ISSUE THREAD

**Issue by iOSliusen** [pikacode/EBBannerView#33]
iOS 13显示不完整

内容部分不显示了

**Comment by pikacode** [comment]
好，马上改😮

**Comment by iOSliusen** [comment]
好的，太感谢了，方便告诉我一下是什么原因导致的吗？猜测是window的缘故，不知是不是

**Comment by pikacode** [comment]
我手机就是13，我的能显示啊，你是否方便录个屏 或 截图

**Comment by iOSliusen** [comment]
Demo 在模拟器上就不弹了

**Comment by iOSliusen** [comment]
https://pan.baidu.com/s/19yTOaxcXMczJ1IPavKstAg

**Comment by pikacode** [comment]
你调用的是哪一个方法

**Comment by iOSliusen** [comment]
项目中用的这个
[EBBannerView showWithContent:msg];

**Comment by pikacode** [comment]
你用的Xcode 是beta版的吗

**Comment by iOSliusen** [comment]
是的,Xcode 11 Beta7

**Comment by pikacode** [comment]
嗯嗯，我安装一个试试。

**Comment by iOSliusen** [comment]
就是说在Xcode 10上跑是没问题吧？

发自我的iPhone

**Comment by pikacode** [comment]
我用的 Xcode 10.3，手机 iOS 13.1 没问题

**Comment by iOSliusen** [comment]
13.1 的真机调试包能传一下吗,谢谢

**Comment by iOSliusen** [comment]
我改了下文件夹名(13.0 ---> 13.1),可以跑了

**Comment by iOSliusen** [comment]
问题出在创建window上

`/ instantiate a UIWindow already associated with a given UIWindowScene instance, with matching frame & interface orientations.
- (instancetype)initWithWindowScene:(UIWindowScene *)windowScene API_AVAILABLE(ios(13.0));
`
用这个创建后可以显示,但是之后界面就不可以点击了

**Comment by pikacode** [comment]
I try try

**Comment by pikacode** [comment]
你好，我看了一下，没有办法初始化啊。。。
UIWindowScene 需要 UISceneSession、UISceneConnectionOptions 这两个参数来初始化，这两个类连初始化方法都没有

**Comment by iOSliusen** [comment]
我这么初始化的,你试试

`        if (@available(iOS 13.0, *)) {
            NSSet * Scenes = [[UIApplication sharedApplication] connectedScenes];
            UIWindowScene * windowScene = [Scenes allObjects].firstObject;
            sharedWindow  = [[self alloc] initWithWindowScene:windowScene];
        } else {
            // Fallback on earlier versions
        }
`

**Comment by pikacode** [comment]
我是这么初始化的
```
UIWindowScene *scene = UIApplication.sharedApplication.keyWindow.windowScene;
[[UIWindow alloc] initWithWindowScene:scene];
```
结果跟你上面说的一样，弹出以后不能点击了

**Comment by iOSliusen** [comment]
> 我是这么初始化的
> 
> ```
> UIWindowScene *scene = UIApplication.sharedApplication.keyWindow.windowScene;
> [[UIWindow alloc] initWithWindowScene:scene];
> ```
> 
> 结果跟你上面说的一样，弹出以后不能点击了

有解决方法吗

**Comment by pikacode** [comment]
- 我估计有可能 beta 版 xcode 苹果的 API 还没有完全暴露出来，等正式版 Xcode 应该可以
- 或者直接用以上方法，在一个空项目里创建一个 window，看是否会同样不能点击，如果也不能点击，说明这么搞就不行

**Comment by iOSliusen** [comment]
okkkkkkkk,我试试能不能解决下这个问题,实在不行就等Xcode正式版

**Comment by iOSliusen** [comment]
如果不用这个 EBBannerWindow  而用 UIWindow 类, 同时消失时将原来的keyWindow设置makeKeyAndVisible,即可解决

**Comment by pikacode** [comment]
你很急的话可以在 EBBannerWindow 的 show hide 里面按照你上面说的方式改改，我今天要上线，明天才有空来调试

**Comment by pikacode** [comment]
也可以看一下今年的开发者大会相关视频，找一下对 UIWindowScene 的介绍。

**Comment by iOSliusen** [comment]
> 你很急的话可以在 EBBannerWindow 的 show hide 里面按照你上面说的方式改改，我今天要上线，明天才有空来调试

我在我们的项目中调好了,暂时没发现什么问题,感谢你的答复

**Comment by panadaW** [comment]
> > 你很急的话可以在 EBBannerWindow 的 show hide 里面按照你上面说的方式改改，我今天要上线，明天才有空来调试
> 
> 我在我们的项目中调好了,暂时没发现什么问题,感谢你的答复

你怎么解决的

**Comment by iOSliusen** [comment]
> > > 你很急的话可以在 EBBannerWindow 的 show hide 里面按照你上面说的方式改改，我今天要上线，明天才有空来调试
> > 
> > 
> > 我在我们的项目中调好了,暂时没发现什么问题,感谢你的答复
> 
> 你怎么解决的

如果不用这个 EBBannerWindow 而用 UIWindow 类, 同时消失时将原来的keyWindow设置makeKeyAndVisible,即可解决

**Comment by panadaW** [comment]
> > > > 你很急的话可以在 EBBannerWindow 的 show hide 里面按照你上面说的方式改改，我今天要上线，明天才有空来调试
> > > 
> > > 
> > > 我在我们的项目中调好了,暂时没发现什么问题,感谢你的答复
> > 
> > 
> > 你怎么解决的
> 
> 如果不用这个 EBBannerWindow 而用 UIWindow 类, 同时消失时将原来的keyWindow设置makeKeyAndVisible,即可解决

这样的话，我发现有一个问题：通知弹框会出现在状态栏下面

**Comment by iOSliusen** [comment]
> > > > > 你很急的话可以在 EBBannerWindow 的 show hide 里面按照你上面说的方式改改，我今天要上线，明天才有空来调试
> > > > 
> > > > 
> > > > 我在我们的项目中调好了,暂时没发现什么问题,感谢你的答复
> > > 
> > > 
> > > 你怎么解决的
> > 
> > 
> > 如果不用这个 EBBannerWindow 而用 UIWindow 类, 同时消失时将原来的keyWindow设置makeKeyAndVisible,即可解决
> 
> 这样的话，我发现有一个问题：通知弹框会出现在状态栏下面

这个问题我也没解决

**Comment by pengshengsongcode** [comment]
大神现在解决这个问题了么？

**Comment by liuqiweim** [comment]
ios13使用demo 点击完全没反应了，请问下是什么原因。

**Comment by talk812** [comment]
wait for solution

**Comment by liuqiweim** [comment]
感谢前面几位大神，总结一下。
1，不用这个 EBBannerWindow 而用 UIWindow 类，即替换原来的BannerWindow。（解决无法弹出）
2，弹出后无法点击的问题，我加了颜色之后发现，新增加的Window没有删除，所以导致点击无效，在hide方法中隐藏sharedWindow 即可，然后在show方法中重新显示sharedWindow既可。
以上，解决。

**Comment by pikacode** [comment]
@liuqiweim 用你的方法，貌似弹窗的时候，页面的其他地方就不能点击了

**Comment by liuqiweim** [comment]
> @liuqiweim 用你的方法，貌似弹窗的时候，页面的其他地方就不能点击了
是的，确实是这样，我没有考虑周全，然后，后续修改，那初始化的时候，设置React为Zero，然后在show 方法中重新设置sharedWindow的尺寸既可在弹窗的时候点击其他地方，
Show方法中
//提前设置sharedWindow Frame
    sharedWindow.frame = CGRectMake(0, 0, weakSelf.fixedWidth, weakSelf.standardHeight + weakSelf.fixedY + 1);
    [UIView animateWithDuration:_maker.showAnimationDuration delay:0 
Hide 
//另外，swipeDownGesture 点击时候也要伸缩sharedWindow Frame 
我的思路就是修改Window的尺寸让后续地方可以点击。
弹出的时候已经可以点击其他地方。


三次修改，NStime 需要用字典keyValue管理，以防重复点击产生多个Timer 
以上。

**Comment by talk812** [comment]
請問什麼時候會更新上CocoaPods

**Comment by liuqiweim** [comment]
> 請問什麼時候會更新上CocoaPods

得先让作者验证过了吧，你自己也可以尝试修改，现在已经满足我的需求了，也希望能继续交流

**Comment by pikacode** [comment]
@iOSliusen @panadaW @pengshengsongcode @liuqiweim @talk812 
各位大佬，现已适配 iOS 13 🎉
https://github.com/pikacode/EBBannerView/releases/tag/1.1.1

更新 pod 仓库即可
1. pod repo update
2. pod install

**Comment by pengshengsongcode** [comment]
牛皮大佬~
