### ISSUE TITLE
Xcode10.3 运行最新版本失败

### ISSUE THREAD

**Issue by BzHuang** [pikacode/EBBannerView#34]
![图片](https://user-images.githubusercontent.com/13215355/67353491-4777cd80-f585-11e9-9131-2ea2cf99784f.png)

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by pikacode** [comment]
@BzHuang 修复了，再试试呢
https://github.com/pikacode/EBBannerView/releases/tag/1.1.2
