### ISSUE TITLE
旧项目Xcode13无法显示

### ISSUE THREAD

**Issue by haochentao** [pikacode/EBBannerView#38]
最近更新了xocde13 发现无法显示了 目前使用1.1.0版本,通过调试时发现keyWindow是没有大小的,目前我改变了下源码,暂时解决了显示问题
+(instancetype)sharedWindow{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        sharedWindow = [UIApplication sharedApplication].delegate.window;
    return sharedWindow;
}
项目中用到的功能不多目前解决了我的问题
同时非常感谢作者!!!

**Comment by canxuedouding** [comment]
直接修改了这个window的懒加载方法吗，

**Comment by pikacode** [comment]
可以更新到最新版本 @haochentao

**Comment by canxuedouding** [comment]
好的.感谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pikacode"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 下午4:30
收件人:&nbsp;"pikacode/EBBannerView"<EBBannerView@noreply.github.com&gt;;
抄送:&nbsp;"忘忧草"<739200859@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [pikacode/EBBannerView] 旧项目Xcode13无法显示 (#38)





 
可以更新到最新版本 @haochentao
