### ISSUE TITLE
IPhoneX 显示异常

### ISSUE THREAD

**Issue by BzHuang** [pikacode/EBBannerView#6]
<img width="322" alt="qq20171201-114842 2x" src="https://user-images.githubusercontent.com/13215355/33467196-b407acf4-d68d-11e7-9e2d-8a7f725eec97.png">

**Comment by pikacode** [comment]
@BzHuang 你好，可以加下 qq 群 345192153 详细说一下吗？

**Comment by pikacode** [comment]
@BzHuang 已经修复了这个 bug，[v1.0.5](https://github.com/pikacode/EBBannerView/releases/tag/1.0.5)
